export const ActionTypes = {
    //INVENTORY
    FETCH_INVENTORY_SUCCESS: "FETCH_INVENTORY_SUCCESS",
    UPDATE_INVENTORY_SUCCESS: "UPDATE_INVENTORY_SUCCESS",
    INVENTORY_LOADING: "INVENTORY_LOADING",
    CREATE_INVENTORY_SUCCESS: "CREATE_INVENTORY_SUCCESS",
    FETCH_INVENTORY_TAGS_SUCCESS: "FETCH_INVENTORY_TAGS_SUCCESS",
    INVENTORY_TAGS_LOADING: "INVENTORY_TAGS_LOADING",
    DELETE_INVENTORY_SUCCESS: "DELETE_INVENTORY_SUCCESS",

    //INVENTORY LOCATIONS
    FETCH_INVENTORY_LOCATIONS_SUCCESS: "FETCH_INVENTORY_LOCATIONS_SUCCESS",
    INVENTORY_LOCATION_SELECTED: "INVENTORY_LOCATION_SELECTED",
    UPDATE_LOCATION_SUCCESS: "UPDATE_LOCATION_SUCCESS",
    DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS",
    CREATE_LOCATION_SUCCESS: "CREATE_LOCATION_SUCCESS",

    //Products
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",

      //Suppliers
      FETCH_SUPPLIER_SUCCESS: "FETCH_SUPPLIER_SUCCESS",
      UPDATE_SUPPLIER_SUCCESS: "UPDATE_SUPPLIER_SUCCESS",
      DELETE_SUPPLIER_SUCCESS: "DELETE_SUPPLIER_SUCCESS",
      CREATE_SUPPLIER_SUCCESS: "CREATE_SUPPLIER_SUCCESS",

            //Products
      FETCH_PURCHASE_REQ_SUCCESS: "FETCH_PURCHASE_REQ_SUCCESS",
      UPDATE_PURCHASE_REQ_SUCCESS: "UPDATE_PURCHASE_REQ_SUCCESS",
      DELETE_PURCHASE_REQ_SUCCESS: "DELETE_PURCHASE_REQ_SUCCESS",
      CREATE_PURCHASE_REQ_SUCCESS: "CREATE_PURCHASE_REQ_SUCCESS",

      //Customer
      CUSTOMER_SIGNUP_SUCCESS : "CUSTOMER_SIGNUP_SUCCESS",

};