export const ActionTypes = {
    //INVENTORY
    FETCH_INVENTORY_SUCCESS: "FETCH_INVENTORY_SUCCESS",
    UPDATE_INVENTORY_SUCCESS: "UPDATE_INVENTORY_SUCCESS",
    INVENTORY_LOADING: "INVENTORY_LOADING",
    CREATE_INVENTORY_SUCCESS: "CREATE_INVENTORY_SUCCESS",
    FETCH_INVENTORY_TAGS_SUCCESS: "FETCH_INVENTORY_TAGS_SUCCESS",
    INVENTORY_TAGS_LOADING: "INVENTORY_TAGS_LOADING",
    DELETE_INVENTORY_SUCCESS: "DELETE_INVENTORY_SUCCESS",

    //INVENTORY LOCATIONS
    FETCH_INVENTORY_LOCATIONS_SUCCESS: "FETCH_INVENTORY_LOCATIONS_SUCCESS",
    INVENTORY_LOCATION_SELECTED: "INVENTORY_LOCATION_SELECTED",
    UPDATE_LOCATION_SUCCESS: "UPDATE_LOCATION_SUCCESS",
    DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS",
    CREATE_LOCATION_SUCCESS: "CREATE_LOCATION_SUCCESS",

    //Products
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",

    //Suppliers
    FETCH_SUPPLIER_SUCCESS: "FETCH_SUPPLIER_SUCCESS",
    UPDATE_SUPPLIER_SUCCESS: "UPDATE_SUPPLIER_SUCCESS",
    DELETE_SUPPLIER_SUCCESS: "DELETE_SUPPLIER_SUCCESS",
    CREATE_SUPPLIER_SUCCESS: "CREATE_SUPPLIER_SUCCESS",

    //Products
    FETCH_PURCHASE_REQ_SUCCESS: "FETCH_PURCHASE_REQ_SUCCESS",
    UPDATE_PURCHASE_REQ_SUCCESS: "UPDATE_PURCHASE_REQ_SUCCESS",
    DELETE_PURCHASE_REQ_SUCCESS: "DELETE_PURCHASE_REQ_SUCCESS",
    CREATE_PURCHASE_REQ_SUCCESS: "CREATE_PURCHASE_REQ_SUCCESS",

    //Orders
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
    DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",

    //Customer
    CUSTOMER_SIGNUP_SUCCESS : "CUSTOMER_SIGNUP_SUCCESS",
    CUSTOMER_UPDATE_SUCCESS : "CUSTOMER_UPDATE_SUCCESS",

    //Cart
    CART_CREATE_SUCCESS : "CART_CREATE_SUCCESS",
    CART_UPDATE_SUCCESS : "CART_UPDATE_SUCCESS",

    FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
    CART_DELETE_SUCCESS : "CART_DELETE_SUCCESS",
    FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  
    //SuperUsers
    FETCH_SUPERUSERS_SUCCESS : "FETCH_SUPERUSERS_SUCCESS",
    SUPERUSERS_LOADING : "SUPERUSERS_LOADING",
    UPDATE_SUPERUSER_SUCCESS: "UPDATE_SUPERUSER_SUCCESS",
    CREATE_SUPERUSER_SUCCESS: "CREATE_SUPERUSER_SUCCESS",
    DELETE_SUPERUSER_SUCCESS: "DELETE_SUPERUSER_SUCCESS",
    SUPERUSER_LOGIN_SUCCESS: "SUPERUSER_LOGIN_SUCCESS",
    SUPERUSER_LOGIN_FAIL: "SUPERUSER_LOGIN_FAIL",
    SUPERUSER_LOGOUT: "SUPERUSER_LOGOUT",
    SUPERUSER_LOGIN_RESET: "SUPERUSER_LOGIN_RESET",

    //EndUsers
    VALIDATE_ENDUSER_SUCCESS: "VALIDATE_ENDUSER_SUCCESS",
    ENDUSER_REGISTER_NEXT: "ENDUSER_REGISTER_NEXT",

};