export const ActionTypes = {
    //INVENTORY
    FETCH_INVENTORY_SUCCESS : "FETCH_INVENTORY_SUCCESS",
    UPDATE_INVENTORY_SUCCESS : "UPDATE_INVENTORY_SUCCESS",
    INVENTORY_LOADING : "INVENTORY_LOADING",
    CREATE_INVENTORY_SUCCESS:"CREATE_INVENTORY_SUCCESS",
    FETCH_INVENTORY_TAGS_SUCCESS:"FETCH_INVENTORY_TAGS_SUCCESS",
    INVENTORY_TAGS_LOADING:"INVENTORY_TAGS_LOADING",
    DELETE_INVENTORY_SUCCESS:"DELETE_INVENTORY_SUCCESS",

    //INVENTORY LOCATIONS
    FETCH_INVENTORY_LOCATIONS_SUCCESS : "FETCH_INVENTORY_LOCATIONS_SUCCESS",
    INVENTORY_LOCATION_SELECTED : "INVENTORY_LOCATION_SELECTED"

};